# Generated by Django 2.1.4 on 2018-12-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='service',
            index_together={('id', 'slug')},
        ),
    ]
