# Generated by Django 2.1.4 on 2018-12-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181223_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='service',
            index_together=set(),
        ),
    ]
